name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      -main
jobs:
  publish:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkouts@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore
      run: dotnet restore ./ci-cd-example.sln

    - name: Build
      run: dotnet build ./ci-cd-example.sln --configuration Release --no-restore

    - name: Publish
      run: dotnet publish ./ci-cd-example.sln --configuration Release --no-build
      
